### ISSUE TITLE
Configure automatic restore of Zitadel database

### ISSUE THREAD

**Issue by Smana** [Smana/cloud-native-ref#469]
After Zitadel's installation process, there are many configurations such as setting an Identity provider.
We should restore these configuration from a dump at cluster startup

**Comment by Smana** [comment]
With the crossplane composition, this is now possible to do that:

```yaml
apiVersion: cloud.ogenki.io/v1alpha1
kind: SQLInstance
metadata:
  name: xplane-zitadel
spec:
  size: "small"
  storageGB: 20
  cnpg:
    instances: 1
    createSuperuser: true
    objectStoreRecovery:
      bucketName: "eu-west-3-ogenki-cnpg-backups"
      path: "zitadel-basebackup-20241106"
    backup:
      schedule: "0 0 * * *"
      bucketName: "eu-west-3-ogenki-cnpg-backups"
  compositionRef:
    name: xsqlinstances.cloud.ogenki.io
```
