### ISSUE TITLE
Brief Description of Enhancement Add Kubescape Headlamp plugin

### ISSUE THREAD

**Issue by Smana** [Smana/cloud-native-ref#840]
### Enhancement Title
Add Kubescape plugin to Headlamp

### Summary

[Kubescape](https://github.com/kubescape/kubescape) is an open-source Kubernetes security platform that scans clusters, YAML manifests, and Helm charts for security risks, compliance violations, and misconfigurations based on multiple frameworks.

### Motivation

Improve security level of our Cloud Native Reference platform

### Detailed Explanation

We'll need to install the operator and configure the plugin installation as described below in the Helm values

```yaml
config:
  pluginsDir: /build/plugins
initContainers:
  - command:
      - /bin/sh
      - '-c'
      - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
    image: quay.io/kubescape/headlamp-plugin:v0.8.1
    name: kubescape-plugin
    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
volumeMounts:
  - name: headlamp-plugins
    mountPath: /build/plugins
volumes:
  - name: headlamp-plugins
    emptyDir: {}
```
